### ISSUE TITLE
x3270: changing the codepage from menu resets the font size 

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#54]
changing the codepage from menu resets the font size 

to reproduce, set large font size
reset codepage

the font size resets.

**Comment by pmattes** [comment]
What code page did you change from, and what code page did you change to? Xt does not do font substitution, so x3270 must use a font that has the right character set. E.g., if you switch from a U.S. code page to a Greek one, x3270 can no longer use the 3270 fonts (though it will use 3270gr if it is available).

**Comment by swhobbit** [comment]
Switch from default (`BRACKET`) to `CP 1047`

**Comment by pmattes** [comment]
Yup, that's a bug. I will get on it shortly.

**Comment by pmattes** [comment]
Fixed in 4.2ga7.

**Comment by Bamboolyj** [comment]
I have a relevant question. I have change the codepage to cp937, but the Chinese character still is a nonsense.

**Comment by pmattes** [comment]
@Bamboolyj, could you provide me with a bit more information?
* What version of x3270 are you running?
* What platform are you running on?
* Could you provide me with a screenshot and data stream trace of the misbehavior?

**Comment by Bamboolyj** [comment]
Hi @pmattes, thanks for your help.
1: I used the latest version of wc3270-noinstall-64 (http://prdownloads.sourceforge.net/x3270/wc3270-4.3ga3-noinstall-64.zip?download)
2: My python called wc3270.exe to run the code.
3: I have checked the relevant file, it told me I need to change the codepage to cp937.  But when i have set the codepage to cp937, it still cannot display Chinese.  it seems i need to change the windows codepage(now it is cp1252) to utf-8, but it is blocking me from doing this operation.
![image](https://github.com/pmattes/x3270/assets/110580583/47e51645-82be-4b27-b5e5-632c9fd5ad10)
![image](https://github.com/pmattes/x3270/assets/110580583/f8fd1c00-aefb-4bb9-bf87-23c0bf6d7ef2)
![image](https://github.com/pmattes/x3270/assets/110580583/079f50ad-b05b-4d02-949f-9bfbdfa1d0b9)

I am looking forward to your reply, it has been blocking me for a long time, many thanks!!!

**Comment by pmattes** [comment]
The local encoding affects only how text files such as keymaps are interpreted when read into wc3270, how text such as trace files is output, and it is the default for text file transfers. It does not affect how text is displayed on the emulated 3270 display screen -- wc3270 switches to UTF-8 internally for that.

The display issue you are probably seeing is a frustrating one. wc3270 uses a Windows Console (the old-fashioned kind, not the new Windows Terminal), and Windows Consoles steadfastly refuse to display Chinese text unless the computer is configured to use Chinese as its display language. I think it worked without that in Windows XP, but not since then.

I'm pretty sure that Windows Terminal does not have this limitation, but I haven't figured out how to cleanly integrate wc3270 with Windows Terminal yet.

Have you tried wx3270?

**Comment by Bamboolyj** [comment]
Thanks for your answer, but my code is based on wc3270 to run. maybe I need to find another way to deal with this problem. thank you

**Comment by pmattes** [comment]
Interesting -- I just checked, and with the right font on Windows 11, wc3270 will display Chinese characters properly. For my test, I used the SimHei font.

**Comment by Bamboolyj** [comment]
wow, how an exciting news!!! could you share more details to me, i want to follow your operate steps to set the args, if there are screenshots even better. it is very important to me. thank you very much.

**Comment by pmattes** [comment]
I'm running Windows 11 22H2. I haven't tried other versions. I have Chinese language support installed (fonts, input methods).

I used the wc3270 4.3 Session Wizard to create a session:
![image](https://github.com/pmattes/x3270/assets/36997446/b230630d-29c0-4b3c-95ec-ae7094e05755)

Once the wc3270 window was open, I had to change the Font explicitly to SimHei. Despite my explicit configuration in the Session Wizard, the window used Lucida Console, which works, but not very well.
![image](https://github.com/pmattes/x3270/assets/36997446/002c75e9-6655-4bfb-8379-19cf9660e27e)

That's pretty much it.
